packaging_format = 2

id = "vikunja"
name = "Vikunja"
description.en = "Self-hosted To-Do list application"
description.fr = "Application de liste de tâches auto-hébergée"

version = "0.20.2~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "GPL-3.0"
website = "https://vikunja.io/"
demo = "https://try.vikunja.io/login"
admindoc = "https://vikunja.io/docs/"
code = "https://kolaente.dev/vikunja/"

[integration]
yunohost = ">= 11.1.15"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    help.en = "If enabled, Vikunja will be accessible by people who do not have an account. This can be changed later via the webadmin."
    help.fr = "Si cette case est cochée, Vikunja sera accessible aux personnes n’ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]
        [resources.sources.back]
        arm64.url = "https://dl.vikunja.io/api/0.20.2/vikunja-v0.20.2-linux-arm64-full.zip"
        arm64.sha256 = "80d217013b11e5e7b2c3be50186abca2d46dac122a45ac69dc5189f7a0163cf2"
        amd64.url = "https://dl.vikunja.io/api/0.20.2/vikunja-v0.20.2-linux-amd64-full.zip"
        amd64.sha256 = "ce6f698134ac33ab307472ab6418043a7e92e1dbc917044f616c4bc6112e3ee0"
        armhf.url = "https://dl.vikunja.io/api/0.20.2/vikunja-v0.20.2-linux-arm-7-full.zip"
        armhf.sha256 = "dceace8dd44baa999ffeb7ff515c5d4108ad064553d58cb0254faed061661ff4"
        i386.url = "https://dl.vikunja.io/api/0.20.2/vikunja-v0.20.2-linux-386-full.zip"
        i386.sha256 = "e334c4203de04cc38f3d123445a93cf1b8b945731302d49392e05faabd1844c6"
        in_subdir = false
        
        [resources.sources.front]
        url = "https://dl.vikunja.io/frontend/vikunja-frontend-0.20.3.zip"
        sha256 = "f95b5d81b25a5dc3e53bbd06aacbabea8b016fb880bd59cfbf689a1dbb364669"
        in_subdir = false

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.show_tile = false
    api.allowed = "visitors"

    [resources.apt]
    packages = "postgresql"

    [resources.database]
    type = "postgresql"
