packaging_format = 2

id = "vikunja"
name = "Vikunja"
description.en = "Self-hosted To-Do list application"
description.fr = "Application de liste de tâches auto-hébergée"

version = "0.21.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "GPL-3.0"
website = "https://vikunja.io/"
demo = "https://try.vikunja.io/login"
admindoc = "https://vikunja.io/docs/"
code = "https://kolaente.dev/vikunja/"

[integration]
yunohost = ">= 11.1.21"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "1500M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    help.en = "If enabled, Vikunja will be accessible by people who do not have an account. This can be changed later via the webadmin."
    help.fr = "Si cette case est cochée, Vikunja sera accessible aux personnes n’ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]
        [resources.sources.back]
        arm64.url = "https://dl.vikunja.io/api/0.20.4/vikunja-v0.21.0-linux-arm64-full.zip"
        arm64.sha256 = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        amd64.url = "https://dl.vikunja.io/api/0.20.4/vikunja-v0.21.0-linux-amd64-full.zip"
        amd64.sha256 = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        armhf.url = "https://dl.vikunja.io/api/0.20.4/vikunja-v0.21.0-linux-arm-7-full.zip"
        armhf.sha256 = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        i386.url = "https://dl.vikunja.io/api/0.20.4/vikunja-v0.21.0-linux-386-full.zip"
        i386.sha256 = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        in_subdir = false
        
        [resources.sources.front]
        url = "https://dl.vikunja.io/frontend/vikunja-frontend-0.21.0.zip"
        sha256 = "ec59d8db8076123028331167357050f73bdb5b41793cf5c47d60acf9f1fddc12"
        in_subdir = false

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.show_tile = false
    api.allowed = "visitors"

    [resources.apt]
    packages = "postgresql"

    [resources.database]
    type = "postgresql"
