test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.4cf807ee10e609d85147ac389ea7f62260c733b2.name = "Upgrade from 0.20.2"